---
- name: Run Load Generator Docker container (Master)
  docker_container:
    name: loadgenerator-master
    image: loadgenerator
    state: started
    ports:
      - "8089:8089"
      - "5557:5557"
    env:
      LOCUST_MODE: "master"
      FRONTEND_ADDR: "{{ frontend_ip }}"

- name: Run Locust Exporter Docker container
  docker_container:
    name: locust-exporter
    image: containersol/locust_exporter:latest
    state: started
    network_mode: host